import {
  CoreValue,
  FeedbackEntry,
  GoalKpi,
  PerformanceCycle,
  PerformanceScorecard,
} from "./types";

export const DEFAULT_PERFORMANCE_CYCLE_ID = "PERF-H1-2026";

export const coreValues: CoreValue[] = [
  {
    id: "G",
    title: "Growth",
    description: "Demonstrates continuous learning, adapts to feedback, and strives for professional development.",
  },
  {
    id: "H",
    title: "Helpfulness",
    description: "Supports students and peers, offers assistance, and contributes to a collaborative environment.",
  },
  {
    id: "O",
    title: "Ownership",
    description: "Takes full accountability for student outcomes and classroom session success.",
  },
  {
    id: "R",
    title: "Reliability",
    description: "Consistently delivers high-quality teaching, prompt attendance, and reliable session timings.",
  },
  {
    id: "T",
    title: "Trustworthiness",
    description: "Acts with integrity, builds trust with students and families, and protects data privacy.",
  },
  {
    id: "W",
    title: "Work Ethics",
    description: "Maintains professional conduct, respects guidelines, and demonstrates commitment to academic excellence.",
  },
];

export const performanceCycles: PerformanceCycle[] = [
  {
    id: "PERF-H2-2025",
    label: "H2 2025 Review",
    reviewWindow: "Jul 2025 - Dec 2025",
    calibrationDate: "2026-01-15",
    status: "Closed",
    note: "Prior cycle closed after calibration and increment recommendations were released.",
  },
  {
    id: "PERF-H1-2026",
    label: "H1 2026 Review",
    reviewWindow: "Jan 2026 - Jun 2026",
    calibrationDate: "2026-05-30",
    status: "Calibration",
    note: "Core-value evaluations are under manager review and calibration is scheduled for the end of May.",
  },
];

export const initialPerformanceScorecards: PerformanceScorecard[] = [
  {
    id: "SCR-101-H1-2026",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-101",
    reviewer: "Admin",
    overallScore: 4.5,
    nextReviewDate: "2026-05-28",
    appraisalStatus: "Calibration Ready",
    trend: "Improving",
    recommendedAction: "Prepare leadership stretch goals and delegate more recurring payroll follow-ups.",
    strengths: ["Closes policy issues fast", "Mentors junior coordinators with high clarity"],
    watchouts: ["Needs stronger delegation on repetitive monthly tasks"],
    managerSummary:
      "Priyanjali has kept HR operations stable while cleaning up process gaps in payroll readiness and onboarding governance.",
    selfSummary:
      "Focused on making HR processes less reactive, but still wants to build a stronger delegation rhythm before the next cycle.",
    valueRatings: [
      {
        valueId: "ownership",
        score: 4.8,
        note: "Takes complete accountability for monthly HR and payroll readiness.",
      },
      {
        valueId: "learner-mindset",
        score: 4.2,
        note: "Applies process retrospectives and converts them into checklists quickly.",
      },
      {
        valueId: "student-first",
        score: 4.4,
        note: "Supports family escalations and cross-team compliance with good judgment.",
      },
      {
        valueId: "team-reliability",
        score: 4.6,
        note: "Keeps managers informed early and protects downstream operations.",
      },
    ],
  },
  {
    id: "SCR-102-H1-2026",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-102",
    reviewer: "Admin",
    overallScore: 4.7,
    nextReviewDate: "2026-05-27",
    appraisalStatus: "Manager Review",
    trend: "Stable",
    recommendedAction: "Add a sharper succession plan for curriculum review bandwidth and mentor one additional tutor lead.",
    strengths: ["Strong academic credibility", "Consistent quality bar across curriculum reviews"],
    watchouts: ["Needs to distribute critical decision-making more evenly across the team"],
    managerSummary:
      "Ramesh continues to anchor the academic function with high standards, particularly on curriculum quality and faculty calibration.",
    selfSummary:
      "Proud of renewal and academic outcomes, with a focus on making the team less dependent on one-person approvals.",
    valueRatings: [
      {
        valueId: "ownership",
        score: 4.7,
        note: "Owns teaching quality and curriculum outcomes with very little escalation.",
      },
      {
        valueId: "learner-mindset",
        score: 4.9,
        note: "Constantly iterates lesson design using cohort performance data.",
      },
      {
        valueId: "student-first",
        score: 4.8,
        note: "Makes decisions with visible focus on learner comprehension and retention.",
      },
      {
        valueId: "team-reliability",
        score: 4.4,
        note: "Reliable under pressure, though some approvals still bottleneck around him.",
      },
    ],
  },
  {
    id: "SCR-103-H1-2026",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-103",
    reviewer: "Priyanjali Sharma",
    overallScore: 3.8,
    nextReviewDate: "2026-05-26",
    appraisalStatus: "Self Review",
    trend: "Improving",
    recommendedAction: "Tighten closure discipline on vendor tasks and improve written handover quality.",
    strengths: ["Responds well to feedback", "Shows improving ownership on daily closures"],
    watchouts: ["Needs more consistency on documentation and deadline control"],
    managerSummary:
      "Vikram is progressing well through probation but still needs tighter follow-through on documentation-heavy work.",
    selfSummary:
      "Feels more confident with operations routines now and wants to improve task planning before deadlines bunch up.",
    valueRatings: [
      {
        valueId: "ownership",
        score: 3.9,
        note: "Owns assigned tasks better than earlier in the cycle, but still misses some closure details.",
      },
      {
        valueId: "learner-mindset",
        score: 4.1,
        note: "Responds well to coaching and incorporates feedback quickly.",
      },
      {
        valueId: "student-first",
        score: 3.6,
        note: "Understands the service impact of ops delays, though consistency still needs work.",
      },
      {
        valueId: "team-reliability",
        score: 3.5,
        note: "Can improve handovers and communication during high-volume weeks.",
      },
    ],
  },
  {
    id: "SCR-101-H2-2025",
    cycleId: "PERF-H2-2025",
    employeeId: "EMP-101",
    reviewer: "Admin",
    overallScore: 4.2,
    nextReviewDate: "2025-12-20",
    appraisalStatus: "Closed",
    trend: "Stable",
    recommendedAction: "Completed cycle.",
    strengths: ["Restored HR process consistency"],
    watchouts: ["Needed faster reporting escalation"],
    managerSummary: "Closed cycle summary archived.",
    selfSummary: "Closed cycle self-reflection archived.",
    valueRatings: [
      { valueId: "ownership", score: 4.3, note: "Strong execution rhythm." },
      { valueId: "learner-mindset", score: 4.0, note: "Responsive to review feedback." },
      { valueId: "student-first", score: 4.1, note: "Supportive escalation handling." },
      { valueId: "team-reliability", score: 4.4, note: "Good cross-team coordination." },
    ],
  },
  {
    id: "SCR-102-H2-2025",
    cycleId: "PERF-H2-2025",
    employeeId: "EMP-102",
    reviewer: "Admin",
    overallScore: 4.6,
    nextReviewDate: "2025-12-20",
    appraisalStatus: "Closed",
    trend: "Stable",
    recommendedAction: "Completed cycle.",
    strengths: ["Protected quality of academic operations"],
    watchouts: ["Needed broader delegation"],
    managerSummary: "Closed cycle summary archived.",
    selfSummary: "Closed cycle self-reflection archived.",
    valueRatings: [
      { valueId: "ownership", score: 4.6, note: "Strong ownership." },
      { valueId: "learner-mindset", score: 4.8, note: "Excellent iteration mindset." },
      { valueId: "student-first", score: 4.7, note: "Very strong learner orientation." },
      { valueId: "team-reliability", score: 4.3, note: "Dependable partner to peers." },
    ],
  },
  {
    id: "SCR-103-H2-2025",
    cycleId: "PERF-H2-2025",
    employeeId: "EMP-103",
    reviewer: "Priyanjali Sharma",
    overallScore: 3.4,
    nextReviewDate: "2025-12-20",
    appraisalStatus: "Closed",
    trend: "At Risk",
    recommendedAction: "Completed cycle.",
    strengths: ["Adapted to new processes"],
    watchouts: ["Needed higher closure consistency"],
    managerSummary: "Closed cycle summary archived.",
    selfSummary: "Closed cycle self-reflection archived.",
    valueRatings: [
      { valueId: "ownership", score: 3.4, note: "Inconsistent task closure." },
      { valueId: "learner-mindset", score: 3.8, note: "Improving through coaching." },
      { valueId: "student-first", score: 3.1, note: "Service impact awareness needs depth." },
      { valueId: "team-reliability", score: 3.3, note: "Communication needs tightening." },
    ],
  },
];

export const initialFeedbackEntries: FeedbackEntry[] = [
  {
    id: "FDB-101-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-101",
    source: "Manager",
    author: "Admin",
    title: "Process ownership remains high",
    summary:
      "Handles sensitive HR and payroll dependencies with very low supervision and escalates compliance risks early.",
    tone: "Positive",
    updatedOn: "2026-05-19",
  },
  {
    id: "FDB-101-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-101",
    source: "Peer",
    author: "Finance Desk",
    title: "Delegation can improve",
    summary:
      "Cross-functional teams would benefit from earlier task distribution during payroll week so fewer items bottleneck with HR.",
    tone: "Constructive",
    updatedOn: "2026-05-21",
  },
  {
    id: "FDB-102-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-102",
    source: "Manager",
    author: "Admin",
    title: "Academic quality leadership is strong",
    summary:
      "Maintains a strong standard for curriculum and tutor calibration while keeping learner outcomes visible.",
    tone: "Positive",
    updatedOn: "2026-05-20",
  },
  {
    id: "FDB-102-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-102",
    source: "Peer",
    author: "Tutor Lead",
    title: "Decision-making load is concentrated",
    summary:
      "More mid-level delegation would improve turnaround on faculty approvals during peak assessment windows.",
    tone: "Constructive",
    updatedOn: "2026-05-22",
  },
  {
    id: "FDB-103-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-103",
    source: "Manager",
    author: "Priyanjali Sharma",
    title: "Visible growth on daily routines",
    summary:
      "Operational discipline is improving, especially on attendance closure and support requests, but documentation still slips under pressure.",
    tone: "Constructive",
    updatedOn: "2026-05-18",
  },
  {
    id: "FDB-103-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-103",
    source: "Self",
    author: "Vikram Aditya",
    title: "Needs stronger planning discipline",
    summary:
      "Recognizes that deadline clustering affects quality and wants tighter planning and written handovers.",
    tone: "Constructive",
    updatedOn: "2026-05-21",
  },
];

export const initialGoalKpis: GoalKpi[] = [
  {
    id: "GL-101-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-101",
    title: "Reduce onboarding turnaround time",
    category: "Process Efficiency",
    target: "Bring average onboarding completion below 3 days",
    progress: 82,
    status: "On Track",
    kpiLabel: "Average onboarding TAT",
    currentValue: "3.4 days",
    targetValue: "3.0 days",
    dueDate: "2026-06-20",
    owner: "HR",
    note: "New checklist is working, but vendor document follow-ups still slow down final closure.",
  },
  {
    id: "GL-101-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-101",
    title: "Publish payroll SOP and escalation matrix",
    category: "Governance",
    target: "Complete 10 of 10 payroll process documents",
    progress: 58,
    status: "Needs Support",
    kpiLabel: "Documentation completion",
    currentValue: "7 / 10",
    targetValue: "10 / 10",
    dueDate: "2026-06-10",
    owner: "HR",
    note: "Waiting on final finance sign-off for two escalation sections.",
  },
  {
    id: "GL-102-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-102",
    title: "Lift advanced math renewal rate",
    category: "Academic Outcome",
    target: "Sustain renewal rate above 92%",
    progress: 96,
    status: "Achieved",
    kpiLabel: "Renewal rate",
    currentValue: "94%",
    targetValue: "92%",
    dueDate: "2026-06-15",
    owner: "Academics",
    note: "Term retention target already exceeded with strong parent feedback.",
  },
  {
    id: "GL-102-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-102",
    title: "Improve tutor calibration readiness",
    category: "Capability Building",
    target: "Move tutor calibration score to 85%",
    progress: 76,
    status: "On Track",
    kpiLabel: "Tutor calibration score",
    currentValue: "79%",
    targetValue: "85%",
    dueDate: "2026-06-28",
    owner: "Academics",
    note: "Two additional review workshops are scheduled before the cycle ends.",
  },
  {
    id: "GL-103-1",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-103",
    title: "Reduce vendor closure backlog",
    category: "Operations",
    target: "Close 95% of open vendor tasks within SLA",
    progress: 63,
    status: "Needs Support",
    kpiLabel: "Task closure within SLA",
    currentValue: "81%",
    targetValue: "95%",
    dueDate: "2026-06-18",
    owner: "Operations",
    note: "Needs tighter prioritization and earlier handovers when workload spikes.",
  },
  {
    id: "GL-103-2",
    cycleId: "PERF-H1-2026",
    employeeId: "EMP-103",
    title: "Improve attendance closure accuracy",
    category: "Execution Quality",
    target: "Reach 98% first-pass attendance closure accuracy",
    progress: 71,
    status: "On Track",
    kpiLabel: "Closure accuracy",
    currentValue: "94%",
    targetValue: "98%",
    dueDate: "2026-06-25",
    owner: "Operations",
    note: "Daily review checkpoints are helping reduce end-of-day errors.",
  },
  {
    id: "GL-101-OLD",
    cycleId: "PERF-H2-2025",
    employeeId: "EMP-101",
    title: "Closed cycle goal archive",
    category: "Archive",
    target: "Completed prior cycle",
    progress: 100,
    status: "Achieved",
    kpiLabel: "Archive",
    currentValue: "Closed",
    targetValue: "Closed",
    dueDate: "2025-12-20",
    owner: "HR",
    note: "Historical record.",
  },
];
