import {
  AttendanceRecord,
  HolidayItem,
  LeaveRequest,
  ShiftAssignment,
  ShiftTemplate,
  WorkPolicy,
} from "./types";

export const DEFAULT_ATTENDANCE_DATE = "2026-05-23";

export const initialAttendanceRecords: AttendanceRecord[] = [
  {
    id: "ATT-2301",
    employeeId: "EMP-101",
    date: "2026-05-23",
    shiftId: "SHIFT-GEN",
    checkIn: "08:56",
    checkOut: "18:14",
    hoursWorked: 8.9,
    status: "Present",
    notes: "Completed payroll audit standup and 1:1 reviews.",
  },
  {
    id: "ATT-2302",
    employeeId: "EMP-102",
    date: "2026-05-23",
    shiftId: "SHIFT-ACA",
    checkIn: "08:03",
    checkOut: "16:58",
    hoursWorked: 8.4,
    status: "Remote",
    notes: "Remote curriculum review and faculty planning calls.",
  },
  {
    id: "ATT-2303",
    employeeId: "EMP-103",
    date: "2026-05-23",
    shiftId: "SHIFT-OPS",
    checkIn: "10:22",
    checkOut: "19:04",
    hoursWorked: 8,
    status: "Late",
    notes: "Delayed by field vendor visit; completed EOD operations closure.",
  },
  {
    id: "ATT-2201",
    employeeId: "EMP-101",
    date: "2026-05-22",
    shiftId: "SHIFT-GEN",
    checkIn: "09:01",
    checkOut: "18:09",
    hoursWorked: 8.6,
    status: "Present",
  },
  {
    id: "ATT-2202",
    employeeId: "EMP-102",
    date: "2026-05-22",
    shiftId: "SHIFT-ACA",
    checkIn: "08:11",
    checkOut: "16:42",
    hoursWorked: 8.2,
    status: "Present",
  },
  {
    id: "ATT-2203",
    employeeId: "EMP-103",
    date: "2026-05-22",
    shiftId: "SHIFT-OPS",
    hoursWorked: 0,
    status: "On Leave",
    notes: "Personal documentation work cleared by reporting manager.",
  },
];

export const initialLeaveRequests: LeaveRequest[] = [
  {
    id: "LEAVE-701",
    employeeId: "EMP-103",
    leaveType: "Casual Leave",
    startDate: "2026-05-29",
    endDate: "2026-05-30",
    days: 2,
    reason: "Family travel and home documentation work.",
    requestedOn: "2026-05-22",
    status: "Pending",
    coverageNote: "Operations inbox handover planned with HR desk.",
  },
  {
    id: "LEAVE-702",
    employeeId: "EMP-102",
    leaveType: "Sick Leave",
    startDate: "2026-05-26",
    endDate: "2026-05-26",
    days: 1,
    reason: "Scheduled medical consultation.",
    requestedOn: "2026-05-21",
    status: "Pending",
    coverageNote: "Recorded lectures already shared with the academics team.",
  },
  {
    id: "LEAVE-703",
    employeeId: "EMP-101",
    leaveType: "Earned Leave",
    startDate: "2026-06-12",
    endDate: "2026-06-13",
    days: 2,
    reason: "Planned personal travel.",
    requestedOn: "2026-05-18",
    status: "Approved",
    coverageNote: "Payroll sign-off delegated to Admin for the cycle.",
  },
];

export const holidayCalendar: HolidayItem[] = [
  {
    id: "HOL-01",
    name: "Bakrid / Eid al-Adha",
    date: "2026-05-27",
    type: "National",
    appliesTo: "All offices",
  },
  {
    id: "HOL-02",
    name: "Founders' Day",
    date: "2026-06-19",
    type: "Company",
    appliesTo: "Corporate and HR operations",
  },
  {
    id: "HOL-03",
    name: "Independence Day",
    date: "2026-08-15",
    type: "National",
    appliesTo: "All teams",
  },
  {
    id: "HOL-04",
    name: "Janmashtami",
    date: "2026-09-03",
    type: "Optional",
    appliesTo: "Optional holiday pool",
  },
  {
    id: "HOL-05",
    name: "Gandhi Jayanti",
    date: "2026-10-02",
    type: "National",
    appliesTo: "All teams",
  },
];

export const shiftTemplates: ShiftTemplate[] = [
  {
    id: "SHIFT-GEN",
    name: "General",
    startTime: "09:00",
    endTime: "18:00",
    weeklyHours: 45,
    mode: "Onsite",
    graceMinutes: 15,
    description: "Default admin and HR coverage with overlap for finance and ops.",
  },
  {
    id: "SHIFT-ACA",
    name: "Academic Early",
    startTime: "08:00",
    endTime: "16:30",
    weeklyHours: 42.5,
    mode: "Hybrid",
    graceMinutes: 10,
    description: "Academic planning shift aligned to tutor and curriculum reviews.",
  },
  {
    id: "SHIFT-OPS",
    name: "Operations B",
    startTime: "10:00",
    endTime: "19:00",
    weeklyHours: 45,
    mode: "Onsite",
    graceMinutes: 10,
    description: "Late-day support for admissions, vendor coordination, and closures.",
  },
  {
    id: "SHIFT-REM",
    name: "Remote Flex",
    startTime: "11:00",
    endTime: "20:00",
    weeklyHours: 40,
    mode: "Remote",
    graceMinutes: 20,
    description: "Outcome-based remote schedule for focused documentation and reviews.",
  },
];

export const initialShiftAssignments: ShiftAssignment[] = [
  {
    id: "ASSIGN-01",
    employeeId: "EMP-101",
    shiftId: "SHIFT-GEN",
    weeklyHours: 45,
    workMode: "Onsite",
    weekOff: "Sunday",
  },
  {
    id: "ASSIGN-02",
    employeeId: "EMP-102",
    shiftId: "SHIFT-ACA",
    weeklyHours: 42.5,
    workMode: "Hybrid",
    weekOff: "Sunday",
  },
  {
    id: "ASSIGN-03",
    employeeId: "EMP-103",
    shiftId: "SHIFT-OPS",
    weeklyHours: 45,
    workMode: "Onsite",
    weekOff: "Sunday",
  },
];

export const workPolicies: WorkPolicy[] = [
  {
    id: "POL-01",
    label: "Full-Day Threshold",
    value: "8h 30m",
    note: "Attendance below threshold is escalated for manager review.",
  },
  {
    id: "POL-02",
    label: "Grace Window",
    value: "15 minutes",
    note: "Late arrivals beyond grace convert to a monitored late check-in.",
  },
  {
    id: "POL-03",
    label: "Core Collaboration",
    value: "11:00 - 16:00",
    note: "Hybrid and remote staff must remain reachable during core hours.",
  },
  {
    id: "POL-04",
    label: "Weekly Cap",
    value: "45 hours",
    note: "Shift plans are aligned to payroll and comp-off tracking.",
  },
];
