import {
  PayrollAdjustment,
  PayrollCycle,
  PayrollPolicy,
  PayslipRecord,
  SalaryStructureTemplate,
  TaxRecord,
} from "./types";

export const DEFAULT_PAYROLL_CYCLE_ID = "CYCLE-2026-05";

export const payrollCycles: PayrollCycle[] = [
  {
    id: "CYCLE-2026-04",
    month: "2026-04",
    payoutDate: "2026-04-30",
    lockDate: "2026-04-27",
    status: "Completed",
    bankAdviceStatus: "Reconciled",
    note: "April cycle closed after attendance and finance reconciliation.",
  },
  {
    id: "CYCLE-2026-05",
    month: "2026-05",
    payoutDate: "2026-05-31",
    lockDate: "2026-05-28",
    status: "Processing",
    bankAdviceStatus: "Queued",
    note: "Variable pay, leave recovery, and bank advice are under final review.",
  },
  {
    id: "CYCLE-2026-06",
    month: "2026-06",
    payoutDate: "2026-06-30",
    lockDate: "2026-06-27",
    status: "In Review",
    bankAdviceStatus: "Pending Upload",
    note: "Draft June cycle opened for attendance import and tax validation.",
  },
];

export const initialPayslipRecords: PayslipRecord[] = [
  {
    id: "PS-2026-04-101",
    cycleId: "CYCLE-2026-04",
    employeeId: "EMP-101",
    workingDays: 26,
    payableDays: 26,
    bonus: 4000,
    deductions: 0,
    reimbursements: 1200,
    taxDeducted: 7800,
    netPay: 69400,
    status: "Sent",
    note: "April payroll released to bank and payslip shared with employee.",
  },
  {
    id: "PS-2026-04-102",
    cycleId: "CYCLE-2026-04",
    employeeId: "EMP-102",
    workingDays: 26,
    payableDays: 26,
    bonus: 6000,
    deductions: 0,
    reimbursements: 1800,
    taxDeducted: 14500,
    netPay: 92300,
    status: "Sent",
  },
  {
    id: "PS-2026-04-103",
    cycleId: "CYCLE-2026-04",
    employeeId: "EMP-103",
    workingDays: 26,
    payableDays: 25,
    bonus: 0,
    deductions: 1250,
    reimbursements: 0,
    taxDeducted: 2800,
    netPay: 34750,
    status: "Generated",
  },
  {
    id: "PS-2026-05-101",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-101",
    workingDays: 26,
    payableDays: 26,
    bonus: 6000,
    deductions: 1200,
    reimbursements: 1800,
    taxDeducted: 7800,
    netPay: 70800,
    status: "Generated",
    note: "Retention bonus included after appraisal freeze.",
  },
  {
    id: "PS-2026-05-102",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-102",
    workingDays: 26,
    payableDays: 26,
    bonus: 8500,
    deductions: 0,
    reimbursements: 2500,
    taxDeducted: 14500,
    netPay: 95500,
    status: "Ready",
    note: "Awaiting final academic incentive sign-off before bank release.",
  },
  {
    id: "PS-2026-05-103",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-103",
    workingDays: 26,
    payableDays: 25,
    bonus: 0,
    deductions: 950,
    reimbursements: 1200,
    taxDeducted: 2800,
    netPay: 36250,
    status: "Draft",
    note: "Leave deduction will lock after balance verification.",
  },
  {
    id: "PS-2026-06-101",
    cycleId: "CYCLE-2026-06",
    employeeId: "EMP-101",
    workingDays: 26,
    payableDays: 26,
    bonus: 0,
    deductions: 0,
    reimbursements: 0,
    taxDeducted: 7800,
    netPay: 72200,
    status: "Draft",
  },
  {
    id: "PS-2026-06-102",
    cycleId: "CYCLE-2026-06",
    employeeId: "EMP-102",
    workingDays: 26,
    payableDays: 26,
    bonus: 0,
    deductions: 0,
    reimbursements: 0,
    taxDeducted: 14500,
    netPay: 84500,
    status: "Draft",
  },
];

export const initialPayrollAdjustments: PayrollAdjustment[] = [
  {
    id: "ADJ-5101",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-101",
    type: "Bonus",
    label: "Quarterly retention bonus",
    amount: 6000,
    status: "Applied",
    owner: "Admin",
    note: "Approved after April appraisal sign-off.",
  },
  {
    id: "ADJ-5102",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-101",
    type: "Deduction",
    label: "Late attendance recovery",
    amount: 1200,
    status: "Applied",
    owner: "HR",
    note: "Recovered against one monitored half-day shortfall.",
  },
  {
    id: "ADJ-5103",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-102",
    type: "Bonus",
    label: "Curriculum leadership incentive",
    amount: 8500,
    status: "Approved",
    owner: "Finance",
    note: "Queued for release with the May salary file.",
  },
  {
    id: "ADJ-5104",
    cycleId: "CYCLE-2026-05",
    employeeId: "EMP-103",
    type: "Deduction",
    label: "Loss of pay adjustment",
    amount: 950,
    status: "Pending",
    owner: "HR",
    note: "Waiting on leave balance confirmation before cycle lock.",
  },
  {
    id: "ADJ-6101",
    cycleId: "CYCLE-2026-06",
    employeeId: "EMP-101",
    type: "Bonus",
    label: "Policy documentation stipend",
    amount: 2500,
    status: "Pending",
    owner: "HR",
    note: "Candidate for off-cycle inclusion after documentation audit.",
  },
];

export const initialTaxRecords: TaxRecord[] = [
  {
    id: "TAX-101",
    employeeId: "EMP-101",
    fiscalYear: "2026-27",
    regime: "Old Regime",
    taxableIncome: 930000,
    projectedTax: 93600,
    tdsYtd: 15600,
    exemptions: 150000,
    lastDepositDate: "2026-05-07",
    pan: "BGHPS1123A",
    form16Status: "In Progress",
  },
  {
    id: "TAX-102",
    employeeId: "EMP-102",
    fiscalYear: "2026-27",
    regime: "New Regime",
    taxableIncome: 1308000,
    projectedTax: 174000,
    tdsYtd: 29000,
    exemptions: 0,
    lastDepositDate: "2026-05-07",
    pan: "AQTPP5512K",
    form16Status: "In Progress",
  },
  {
    id: "TAX-103",
    employeeId: "EMP-103",
    fiscalYear: "2026-27",
    regime: "New Regime",
    taxableIncome: 516000,
    projectedTax: 33600,
    tdsYtd: 5600,
    exemptions: 0,
    lastDepositDate: "2026-05-07",
    pan: "DJSVA8120P",
    form16Status: "Ready",
  },
];

export const salaryStructureTemplates: SalaryStructureTemplate[] = [
  {
    id: "STRUCT-01",
    title: "Core Staff Fixed Pay",
    targetGroup: "HR, Operations, and Finance teams",
    fixedShare: 78,
    allowanceShare: 14,
    statutoryShare: 8,
    reviewWindow: "Annual revision in April",
    payoutMode: "Monthly bank transfer",
    note: "Default mix for support functions with limited variable components.",
  },
  {
    id: "STRUCT-02",
    title: "Academic Leadership Blend",
    targetGroup: "Academic heads and tutor leads",
    fixedShare: 73,
    allowanceShare: 17,
    statutoryShare: 10,
    reviewWindow: "Term-based review",
    payoutMode: "Monthly payout with incentive bucket",
    note: "Preserves a high fixed base while keeping room for role-linked incentives.",
  },
  {
    id: "STRUCT-03",
    title: "Probation Control Sheet",
    targetGroup: "New joins under probation",
    fixedShare: 81,
    allowanceShare: 9,
    statutoryShare: 10,
    reviewWindow: "Confirmation checkpoint",
    payoutMode: "Released after attendance lock",
    note: "Used until confirmation and tax declarations are stabilized.",
  },
];

export const payrollPolicies: PayrollPolicy[] = [
  {
    id: "POL-501",
    label: "Attendance Lock",
    value: "3 days before payout",
    note: "Changes after the lock date move to off-cycle corrections.",
  },
  {
    id: "POL-502",
    label: "Reimbursement Cutoff",
    value: "25th of every month",
    note: "Expense claims after cutoff roll forward to the next cycle.",
  },
  {
    id: "POL-503",
    label: "Bank Advice Upload",
    value: "T-1 business day",
    note: "Salary file is uploaded after finance validation and tax checks.",
  },
];
